title: Efficient Deep Learning Book
# email: feedback@efficientdlbook.com
description: >- # this means to ignore newlines until "baseurl:"
  Companion webpage to the book "Efficient Deep Learning".
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://efficientdlbook.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "EfficientDL"
github_username:  EfficientDL

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed